# Generated by Django 4.2.1 on 2023-05-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lilith', '0004_alter_comentario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-create']},
        ),
    ]
