# Generated by Django 4.2.1 on 2023-05-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lilith', '0005_alter_comentario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
