# Generated by Django 4.2.1 on 2023-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lilith', '0006_comentario_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manchete', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
    ]
